Controllers/ActorController.cs
using Eticket.Models;
using Eticket.Repository;
using Eticket.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Eticket.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ActorController : Controller
    {
        private readonly IActorRepository actorRepository;
        private readonly IMovieRepository movieRepository;

        public ActorController(IActorRepository actorRepository,IMovieRepository movieRepository)
        {
            this.actorRepository = actorRepository;
            this.movieRepository = movieRepository;
        }
        [AllowAnonymous]
        public IActionResult Index()
        {
            var actor=actorRepository.Get().ToList();
            return View(actor);
        }
        [AllowAnonymous]
        public IActionResult DetailsActor(int id)
        {
            var actor = actorRepository.GetOne(e => e.Id == id);

            return View(actor);

        }

        public IActionResult Create() 
        {
            return View();
        
        }
        [HttpPost]
        public IActionResult Create(Actor actor, IFormFile file) 
        {
            ModelState.Remove("ProfilePicture");
            
            ModelState.Remove("Movies");

            if (ModelState.IsValid)
            {
                if (file != null && file.Length > 0)
                {
                    // Genereate name
                    var fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);

                    // Save in wwwroot
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\cast", fileName);

                    using (var stream = System.IO.File.Create(filePath))
                    {
                        file.CopyTo(stream);
                    }

                    // Save in db
                    actor.ProfilePicture = fileName;
                }

                actorRepository.Create(actor);


                TempData["success"] = "Add Actor successfuly";

                return RedirectToAction("Index");
            }
            return View(actor);


        }


        public IActionResult Edit(int id)
        {
            var actor = actorRepository.GetOne(e => e.Id == id);
            return View(actor);
        }
        [HttpPost]
        public IActionResult Edit(Actor actor, IFormFile? file)
        {
            ModelState.Remove("ProfilePicture");
            ModelState.Remove("movies");
            

            var oldActor = actorRepository.GetOne(e => e.Id == actor.Id, tracked: false);

            if (ModelState.IsValid)
            {
                if (file != null && file.Length > 0)
                {
                    // Genereate name
                    var fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);

                    // Save in wwwroot
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\cast", fileName);

                    using (var stream = System.IO.File.Create(filePath))
                    {
                        file.CopyTo(stream);
                    }

                    // Delete old img
                    var oldPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\cast", oldActor.ProfilePicture);
                    if (System.IO.File.Exists(oldPath))
                    {
                        System.IO.File.Delete(oldPath);
                    }

                    actor.ProfilePicture = fileName;
                }
                else
                {
                    actor.ProfilePicture = oldActor.ProfilePicture;
                }

                actorRepository.Edit(actor);

                TempData["success"] = "Update actor successfuly";

                return RedirectToAction("Index");
            }

            actor.ProfilePicture = actor.ProfilePicture;

            return View(actor);
        }

        public IActionResult Delete(int id)
        {
            var actor = actorRepository.GetOne(e => e.Id == id);
            if (actor == null) return RedirectToAction("NotFoundPage", "Home");
            
            actorRepository.Delete(actor);
            TempData["success"] = "Deleted actor successfully";
            return RedirectToAction("Index");
        }



    }
}

Controllers/MovieController.cs
using Eticket.Models;
using Eticket.Repository;
using Eticket.Repository.IRepository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace Eticket.Controllers
{
    [Authorize(Roles = "Admin")]
    public class MovieController : Controller
    {
        private readonly IMovieRepository movieRepository;
        private readonly ICategoryRepository categoryRepository;
        private readonly ICinemaRepository cinemaRepository;
        private readonly IActorRepository actorRepository;
        

        public MovieController(IMovieRepository movieRepository,ICategoryRepository categoryRepository
            ,ICinemaRepository cinemaRepository,IActorRepository actorRepository )
        {
            this.movieRepository = movieRepository;
            this.categoryRepository = categoryRepository;
            this.cinemaRepository = cinemaRepository;
            this.actorRepository = actorRepository;
            
        }
        [AllowAnonymous]
        public IActionResult Index(int page=1)
        {
            var movies=movieRepository.Get(includeProps: [e => e.Category, e => e.Cinema]).ToList();
            movies=movies.Skip((page-1)*8).Take(8).ToList();       
            return View(movies);
        }
       
        public IActionResult Create()
        {
            var categories = categoryRepository.Get().ToList();
            var cinemas = cinemaRepository.Get().ToList();
            var actors = actorRepository.Get().ToList();
            ViewBag.Category = categories;
            ViewBag.Cinema = cinemas;
            ViewBag.Actor = actors;

            return View(new Movie());
        
        }
        [HttpPost]
        public IActionResult Create(Movie movie,IFormFile? file)
        {
            ModelState.Remove("ImgUrl");
            ModelState.Remove("Category");
            ModelState.Remove("Cinema");
            ModelState.Remove("Actors");
            ModelState.Remove("actorsMovies");

            if (ModelState.IsValid)
            {
                if (file != null && file.Length > 0)
                {
                    // Genereate name
                    var fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);

                    // Save in wwwroot
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\movies", fileName);

                    using (var stream = System.IO.File.Create(filePath))
                    {
                        file.CopyTo(stream);
                    }

                    // Save in db
                    movie.ImgUrl = fileName;



                }
                movieRepository.Create(movie);
                TempData["success"] = "Add Movie successfuly";
                return RedirectToAction("Index");

            }
            movieRepository.Create(movie);

            return View(movie);

        }




        public IActionResult Edit(int id)
        {
            var movie = movieRepository.GetOne(x => x.Id == id);
            if (movie == null)
            {
                return RedirectToAction(nameof(Index));
            }
            var categories = categoryRepository.Get().ToList();
            var cinemas = cinemaRepository.Get().ToList();
            var actors = actorRepository.Get().ToList();
            ViewBag.Category = categories;
            ViewBag.Cinema = cinemas;
            ViewBag.Actor = actors;




            return View(movie);

        }
        [HttpPost]
        public IActionResult Edit(Movie movie, IFormFile file)
        {

            ModelState.Remove("ImgUrl");
            ModelState.Remove("Category");
            ModelState.Remove("Cinema");

            var oldMovie = movieRepository.GetOne(e => e.Id == movie.Id);

            if (ModelState.IsValid)
            {
                if (file != null && file.Length > 0)
                {
                    // Genereate name
                    var fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);

                    // Save in wwwroot
                    var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\movies", fileName);

                    using (var stream = System.IO.File.Create(filePath))
                    {
                        file.CopyTo(stream);
                    }

                    // Delete old img
                    var oldPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images\\movies", oldMovie.ImgUrl);
                    if (System.IO.File.Exists(oldPath))
                    {
                        System.IO.File.Delete(oldPath);
                    }

                    movie.ImgUrl = fileName;
                }
                else
                {
                    movie.ImgUrl = oldMovie.ImgUrl;
                }

                movieRepository.Edit(movie);

                TempData["success"] = "Update Movie successfuly";

                return RedirectToAction("Index");
            }

            movie.ImgUrl = oldMovie.ImgUrl;
            var categories = categoryRepository.Get().ToList();
            ViewBag.category = categories;


            var cinemas = cinemaRepository.Get().ToList();
            ViewBag.cinema = cinemas;


            return RedirectToAction("Index");



        }

        public IActionResult Delete(int id)
        {
            var movie = movieRepository.GetOne(filter: e => e.Id == id);
            if (movie != null)
            {
                movieRepository.Delete(movie);

                TempData["success"] = "Delete Movie successfuly";

                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction("NotFoundSearch", "Home");




        }



    }
}

Controllers/UserController.cs
using Eticket.Models;
using Eticket.Models.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Eticket.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly RoleManager<IdentityRole> roleManager;

        public UserController(UserManager<ApplicationUser> userManager,RoleManager<IdentityRole> roleManager)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
        }
        public IActionResult Index(string? Account)
        {
            if (Account == null)
            {
                return View(userManager.Users.ToList());
            }

            var Users = userManager.Users.Where(e =>
                 e.Email.Contains(Account) || e.UserName.Contains(Account)).ToList();
            if (Users.Any())
            {

                return View( Users);
            }

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> SearchForUser(string account)
        {
            if (ModelState.IsValid)
            {
                return RedirectToAction("Index", new { Account = account });

            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> blockUser(string userId)
        {
            var user = await userManager.FindByIdAsync(userId);
            if (user != null)
            {
                await userManager.SetLockoutEnabledAsync(user, true);
                var result = await userManager.SetLockoutEndDateAsync(user, DateTime.Now.AddYears(100));
                //await userManager.SetLockoutEnabledAsync(user, false);
                if (result.Succeeded)
                {
                    user.ISBlocked = true;
                    await userManager.UpdateAsync(user);
                    TempData["success"] = "The user has been blocked succefully";
                    var allUser = userManager.Users.ToList();
                    return View("Index", allUser);
                }
                TempData["error"] = "The user has not been blocked";
                var allUser2 = userManager.Users.ToList();
                return View("Index", allUser2);
            }
            return RedirectToAction("NotFoundSearh");
        }

        public async Task<IActionResult> unBlockUser(string userId)
        {
            var user = await userManager.FindByIdAsync(userId);
            if (user != null)
            {
                //await userManager.SetLockoutEnabledAsync(user, true);
                var result = await userManager.SetLockoutEndDateAsync(user, null);
                await userManager.SetLockoutEnabledAsync(user, false);

                if (result.Succeeded)
                {
                    user.ISBlocked = false;
                    await userManager.UpdateAsync(user);
                    TempData["success"] = "The user is not blocked from thd site";
                    var allUser = userManager.Users.ToList();
                    return View("Index", allUser);
                }
                TempData["error"] = "something error has happened";

                var allUser2 = userManager.Users.ToList();
                return View("Index", allUser2);
            }
            return RedirectToAction("NotFoundPage", "home");
        }
        [HttpGet]
        public async Task<IActionResult> AddToRole(string userId)
        {
            var user = await userManager.FindByIdAsync(userId);
            var role = await userManager.GetRolesAsync(user);
            var roles = roleManager.Roles.ToList();
            return View(new AddUserToRoleVM()
            {
                Id = user.Id,
                Name = user.Name,
                Role = string.Join("", role),
                Roles = roles
            });
        }
        [HttpPost]
        public async Task<IActionResult> AddToRole(AddUserToRoleVM userfrmVM)
        {

            var user = await userManager.FindByIdAsync(userfrmVM.Id);
            if (user != null)
            {
                var oldRoles = await userManager.GetRolesAsync(user);
                await userManager.RemoveFromRolesAsync(user, oldRoles);
                var result = await userManager.AddToRoleAsync(user, userfrmVM.Role);
                if (result.Succeeded)
                {
                    TempData["success"] = "The User Role Has Been Changed";
                }
                return View("Index", userManager.Users.ToList());
            }
            return RedirectToAction("NotFoundPage", "home");
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> UserManeger


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <title>  @ViewData["Title"] - Eticket</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Eticket.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <img src="~/images/logo.png" />
            
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Eticket</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Management System</a>
                                <div class="dropdown-menu">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Cinema" asp-action="Index">Cinemas</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">Movies</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Actor" asp-action="Index">Actors</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User</a>
                                    
                                </div>

                            </li>
                        }

                        <a class="btn" href="/Cart/Index"><i class="bi bi-cart4 bg-light"></i></a>

                    </ul>

                        <ul class="navbar-nav " >

                            @if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Profile"><img src="~/images/@UserManeger.GetUserAsync(User).Result.photo" width="20px" /> Welcome @User.Identity.Name</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                                </li>
                            }
                            else
                            {



                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                                </li>
                            }

                        </ul>

                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Eticket - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>